version: '3.8'

services:
  kf_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - kfm_network
networks:
  kfm_network:
    external: true




