FROM node:20-alpine3.18 as imagekdbv3
WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN npm install pnpm -g
RUN pnpm config set store-dir /root/.pnpm-store
RUN \
  if [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile; \
  else echo "Lockfile not found. Install package.json file" && pnpm i; \
  fi

COPY . .

RUN ./node_modules/.bin/vite build --mode development

FROM nginx:alpine

COPY --from=imagekdbv3 /app/dist /usr/share/nginx/html
RUN rm -rf /app && \
 rm -rf /root/.cache

EXPOSE 80

ENV PORT 80
