FROM node:20-alpine as deps
RUN corepack enable
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN  pnpm config set store-dir /root/.pnpm-store && pnpm i --frozen-lockfile  && rm -rf /root/.cache



FROM deps as builder
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN pnpm build --mode development && pnpm fetch &&  pnpm i --offline --prod --ignore-scripts


FROM builder as runner
WORKDIR /app
FROM nginx:1.21.6-alpine
COPY --from=runner /app/dist /usr/share/nginx/html
EXPOSE 80