version: '3.8'

services:
  kf_roles:
    #scale: 5
    build:
      context: ./kf_roles
      dockerfile: dockerfile
    ports:
      - 3005:3005
    volumes:
      - /Users/minhnguyen/Documents/works/KFM/kfm-devops/week3/backend/kf_roles/config.json:/home/node/app/config.json
      - /Users/minhnguyen/Documents/works/KFM/kfm-devops/week3/backend/kf_roles/nodemon.dev.json:/home/node/app/nodemon.json
      - /Users/minhnguyen/Documents/works/KFM/kfm-devops/week3/backend/kf_roles/start.sh:/start.sh
    restart: unless-stopped
    entrypoint: ./start.sh
    depends_on:
      - udp-server
    networks:
      - kfm_network

  kf_users:
    #scale: 5
    build:
      context: ./kf_users
      dockerfile: dockerfile
    image: kf_image_users
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - /Users/minhnguyen/Documents/works/KFM/kfm-devops/week3/backend/kf_users/config.json:/home/node/app/config.json
      - /Users/minhnguyen/Documents/works/KFM/kfm-devops/week3/backend/kf_users/nodemon.dev.json:/home/node/app/nodemon.json
      - /Users/minhnguyen/Documents/works/KFM/kfm-devops/week3/backend/kf_users/start.sh:/start.sh
    restart: unless-stopped
    entrypoint: ./start.sh
    depends_on:
      - udp-server
    networks:
      - kfm_network

  udp-server:
    build:
      context: ./server-udp
      dockerfile: dockerfile
    image: kf_udp_server
    ports:
      - "1234:1234/udp"
    command: node index
    networks:
      - kfm_network

  jaeger-rb-consume:
    build:
      context: ./jaeger-rb-consume
      dockerfile: dockerfile
    image: kf_jaeger-rb-consume
    ports:
      - "3939:3939"
    command: node index
    networks:
      - kfm_network

  kfm_mariadb:
    container_name: kfm_mariadb
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    restart: always
    volumes:
      - kfm_db:/var/lib/mysql
    networks:
      - kfm_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - kfm_network
  # haproxy:
  #     build: 
  #       context: ./haproxy
  #       dockerfile: dockerfile
  #     ports:
  #       - "80:80"
  #     networks:
  #         - kfm_network  


volumes:
  kfm_db:
    name: kfm_db
  rabbitmq_data:
    name: rabbitmq_data


networks:
  kfm_network:
    external: true
