version: '3.8'

services:

  nginx:
      build:
        context: .
        dockerfile: dockerfile
      env_file:
        - .env
      ports:
        - $PORT_NGINX_HOST:$PORT_NGINX_CONTAINER
      volumes:
        # - ./nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - kfm_network   

networks:
  kfm_network:
    external: true