version: '1.0'

services:
  haproxy:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    image: haproxy
    ports:
      - $PORT_HAPROXY_CONTAINER:$PORT_HAPROXY_HOST
    # volumes:
    #   - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - kfm_network
networks:
  kfm_network:
    external: true