FROM nginx:latest

# Cài đặt Docker client
RUN apt-get update && apt-get install -y docker.io
RUN apt-get update && apt-get install -y procps

# Copy script vào image
COPY nginx-config-gen.sh /usr/local/bin/nginx-config-gen.sh
COPY start.sh /usr/local/bin/start.sh

# Cấp quyền thực thi cho script
RUN chmod +x /usr/local/bin/nginx-config-gen.sh /usr/local/bin/start.sh

# Mở cổng 80
EXPOSE 80

# Thực thi script khởi động khi container được khởi chạy
CMD ["/usr/local/bin/start.sh"]
