version: '3.8'

services:
  kfm_mariadb:
    container_name: kfm_mariadb
    image: mariadb
    ports:
        - 3306:3306
    env_file:
      - .env
    environment:
        MARIADB_USER: $MARIADB_USER
        MARIADB_PASSWORD: $MARIADB_PASSWORD
        MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    restart: always
    volumes:
      - kfm_db:/var/lib/mysql
    networks:
      - kfm_network

  kf_users:
    scale: 3
    build:
      context: .
      dockerfile: dockerfile
    image: kf_image_users
    env_file:
      - .env
    volumes:
      - ./config.json:/home/node/app/config.json
      - ./nodemon.dev.json:/home/node/app/nodemon.json
    restart: unless-stopped
    depends_on:
      - kfm_mariadb
    networks:
      - kfm_network
    
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - $PORT_NGINX_HOST:$PORT_NGINX_CONTAINER
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/start.sh:/usr/local/bin/start.sh:ro
  #   depends_on:
  #     - kfm_mariadb
  #   networks:
  #     - kfm_network   
  #   command: ["/usr/local/bin/start.sh"]    

volumes:
  kfm_db:
    name: kfm_db

networks:
  kfm_network:
    external: true




