version: '3.8'

services:
  kf_leadboarder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:81
    restart: unless-stopped
    networks:
      - kfm_network
networks:
  kfm_network:
    external: true
